# Fallback config, overridden by env vars if present
[llm]
provider = "ollama"
api = "${OLLAMA_BASE_URL}"
auth_header = "${OLLAMA_AUTH}"
model = "${MODEL}"

[search]
url = "${SEARXNG_API_URL}"

[server]
host = "0.0.0.0"
port = 3000
