version: "3.9"
services:
  perplexica:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Ollama model endpoint + auth
      - OLLAMA_BASE_URL=https://ollamapi.e4eweb.space/api/generate
      - OLLAMA_AUTH=Basic ZTRlYWk6MzRlQWlAMjAyNQ==
      - MODEL=gemma:3-12b
      # Public SearXNG API endpoint (JSON format)
      - SEARXNG_API_URL=https://searx.be/search?format=json
    restart: unless-stopped
