version: "3.8"

services:
  web:
    build: .
    container_name: fastapi-search
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    restart: always
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

volumes:
  ollama_data:
